config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :projects, shallow: true do
		resources :containers do
			member do
		    put 'start'
		    delete 'stop'
		  end
		end
		member do
	    put 'start_codebox'
	    delete 'stop_codebox'
	  end
	end
	root 'projects#index'
	get 'api/refresh/:api_key', :to => 'api#refresh', defaults: { format: 'json' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/container.rb
require 'containerbase'

class Container < ApplicationRecord
  belongs_to :project
	include ContainerBase

	def mount_name
		return project.mount_name + '/' + id.to_s
	end

	def host_port
		return 9000 + id
	end
end

app/models/project.rb
require 'ezicontroller'
require 'containerbase'

class Project < ApplicationRecord
	has_many :containers, dependent: :restrict_with_exception
  belongs_to :user
	include ContainerBase

	def base_dir
		return Settings.filesystem.base
	end

	def mount_name
		return base_dir + '/' + user.id.to_s + '/' + id.to_s
	end

	def host_port
		return 8000 + id
	end
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :trackable, :validatable
	has_many :projects, dependent: :restrict_with_exception

	def name
		n = super
		if n == nil
			return email
		end
		return n
	end

	#Custom validation
	validate :presence_domain_email

	def presence_domain_email
		#if email domain not on valid list then return an error.

		valid = false

		Settings.valid_emails.each do |test_text|
			test = Regexp.new(test_text, Regexp::IGNORECASE)
			if test.match(email)
				valid = true
			end
		end

		# Generate an error if the domain is not valid
		unless valid
			errors.add(:email, 'does not match any approved condition.')
		end
	end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
	def refresh
		respond_to do |format|
			if ApiController.is_key_valid(params[:api_key])
				msg = {:responce => 'ok'}
				ApiController.send_updates_to_proxy
			else
				msg = {:responce => 'badkey'}
			end
			format.json { render :json => msg }
		end
	end

	def self.api_key
		return Settings.proxy.api_key
	end

	def self.proxy
		return Settings.networking.proxy
	end

	def self.is_key_valid(key)
		return api_key == key
	end

	def self.send_updates_to_proxy
		require 'net/http'

		projects_srv = Settings.networking.docker.codeboxes
		containers_srv = Settings.networking.docker.containers

		projects_data = {}
		projects = Project.all
		projects.each do |proj|
			controller = proj.controller
			if controller != nil && controller.running
				projects_data[proj.id] = {:address => "http://" + projects_srv + ":" + proj.host_port.to_s}
			end
		end

		containers_data = {}
		containers = Container.all
		containers.each do |cont|
			controller = cont.controller
			if controller != nil && controller.running
				containers_data[cont.id] = {:address => "http://" + containers_srv + ":" + cont.host_port.to_s}
			end
		end

		data = {
				:api_key => api_key,
				:projects => projects_data,
				:containers => containers_data
		}.to_json

		uri = URI.parse(proxy + '/proxy-api/setproject/' + URI.escape(data))
		resp = Net::HTTP.get(uri)
	end

	private_class_method :api_key
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
	before_action :authenticate_user!

	def new
		@project = Project.find(params[:project_id])
		@container = Container.new
	end

	def show
		@container = Container.find(params[:id])
		@project = @container.project
		@running = @container.running
	end

	def create
		@project = Project.find(params[:project_id])
		@container = @project.containers.create(container_params)

		if @container.save
			mount_name = @container.mount_name
			host_port = @container.host_port

			require 'ezicontroller'
			container = EziController.new :create => true,
																		:binds => [mount_name + ':/opt/data'],
																		:ports => {'80/tcp' => host_port.to_s},
																		:image => 'php7-mariadb-apache-opensuse'
			@container.docker_id = container.id
			@container.save

			# redirect_to project_containers_path(@project)
			redirect_to @container
		else
			render 'new'
		end
	end

	def destroy
		@container = Container.find(params[:id])
		@project = @container.project

		if @container.docker_id != nil then
			begin
				container = EziController.new :name => @container.docker_id
				container.raw.delete(:force => true)
			rescue Docker::Error::NotFoundError
				# why do we care? We were only going to delete it anyway.
			end
		end

		@container.destroy
		redirect_to project_containers_path(@project)
	end

	def start
		@container = Container.find(params[:id])
		controller = @container.controller

		if controller != nil then
			controller.raw.start
		end

		ApiController.send_updates_to_proxy
		redirect_to @container
	end

	def stop
		@container = Container.find(params[:id])
		controller = @container.controller

		if controller != nil then
			controller.raw.stop
		end

		ApiController.send_updates_to_proxy
		redirect_to @container
	end

	private
	def container_params
		params.require(:container).permit(:name, :description)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :authenticate_user!

	def initialize
		super
		@codebox_base = '/codebox/';
	end

	def new
		@project = Project.new
	end

	def index
		@user = current_user
		@projects = @user.projects
	end

	def show
		@project = Project.find(params[:id])
		@containers = @project.containers
		@user = @project.user
		@running = false

		if @project.docker_id != nil then
			begin
				container = EziController.new :name => @project.docker_id
				@running = container.running
			rescue
			end
		end
	end

	def create
		@user = current_user
		@project = @user.projects.create(project_params)

		mount_name = @project.mount_name
		host_port = @project.host_port

		if @project.save
			require 'ezicontroller'
			container = EziController.new :create => true,
					:binds => [mount_name + ':/opt/data'],
					:ports => {'8000/tcp' => host_port.to_s},
					:image => 'icecreammatt/codebox',
					:command => ["run", "/opt/data"]
			@project.docker_id = container.id
			@project.save

			redirect_to [@project]
		else
			render 'new'
		end
	end

	def destroy
		@project = Project.find(params[:id])
		@user = @project.user
		if @project.containers.length != 0
			redirect_to projects_path
			return
		end

		if @project.docker_id != nil then
			begin
				container = EziController.new :name => @project.docker_id
				container.raw.delete(:force => true)
			rescue Docker::Error::NotFoundError
				# why do we care? We were only going to delete it anyway.
			end
		end

		@project.destroy
		redirect_to projects_path
	end

	def start_codebox
		@project = Project.find(params[:id])
		controller = @project.controller

		if controller != nil then
			controller.raw.start
		end

		ApiController.send_updates_to_proxy
		redirect_to project_path(@project)
	end

	def stop_codebox
		@project = Project.find(params[:id])
		controller = @project.controller

		if controller != nil then
			controller.raw.stop
		end

		ApiController.send_updates_to_proxy
		redirect_to project_path(@project)
	end

	private
		def project_params
			params.require(:project).permit(:name, :description)
		end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/containers/new.html.erb
<h1>Add Container for <%= @project.name %></h1>

<% if @container.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@container.errors.count, "error") %> prohibited
      this container from being saved:
    </h2>
    <ul>
      <% @container.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for :container, url: project_containers_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', project_path(@project) %>

app/views/containers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @container.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @container.description %>
</p>

<p>
  <strong>Docker ID:</strong>
  <%= @container.docker_id %>
</p>

<% if @running %>
Container is running. <%= link_to 'Open Container', container_path + '/view/', :target => :_blank
%> | <%= link_to 'Stop', stop_container_path(@container), method: :delete, data: {
	confirm: 'Are you sure you want to stop the container?' } %><br/>
<% else %>
Container is stopped. <%= link_to 'Start', start_container_path(@container), method: :put %>
<% end %>

<br/>
<br/>
<%= link_to 'Edit', edit_container_path %>
| <%= link_to 'Destroy', container_path,
				method: :delete,
				data: { confirm: 'Are you sure?' } %>
| <%= link_to 'Back', project_path(@project) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

		<%= stylesheet_link_tag    'app.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<header>
			<span class="title">CodeFreely</span>
			<% if user_signed_in? %>
				<%= link_to '<span class="option">Log out</span>'.html_safe, destroy_user_session_path, method: :delete %>
				<%= link_to '<span class="option">Profile</span>'.html_safe, edit_user_registration_path, method: :get %>
			<% else %>
				<%= link_to '<span class="option">Log in</span>'.html_safe, new_user_session_path, method: :get %>
			<% end %>
		</header>
		<% if alert %>
		<div class="notification alert"><%= alert %></div>
		<% end %>
		<% if notice %>
		<div class="notification notice"><%= notice %></div>
		<% end %>
		<div id="content">
	    <%= yield %>
		</div>
  </body>
</html>

app/views/projects/index.html.erb
<p>
	Projects for <%= @user.name %>
</p>

<table>
<% @projects.each do |project| %>
	<tr>
		<td><%= project.name %></td>
		<td><%= project.description %></td>
		<td><%= link_to 'Show', project_path(project) %></td>
		<td><%= link_to 'Edit', edit_project_path(project) %></td>
		<td><%= link_to 'Destroy', project_path(project),
						method: :delete,
						data: { confirm: 'Are you sure?' } %></td>
	</tr>
<% end %>
</table>

<br/>
<%= link_to 'Add Project', new_project_path %>

app/views/projects/new.html.erb
<h1>Add Project</h1>

<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@project.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for :project, url: projects_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Codebox Docker ID:</strong>
  <%= @project.docker_id %>
</p>

<% if @running %>
Codebox editor is running. <%= link_to 'Open Codebox', @codebox_base + @project.id.to_s + '/', :target => :_blank
%> | <%= link_to 'Stop', stop_codebox_project_path(@project), method: :delete,
 	data: { confirm: 'Are you sure? Any active users will be kicked.' } %><br/>

<% else %>
Codebox editor is stopped. <%= link_to 'Start', start_codebox_project_path(@project), method: :put %>
<% end %>

<p><b>Containers:</b></p>

<table>
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Status</th>
		<th>Toggle</th>
		<th>View</th>
		<th>Open</th>
	</tr>

	<% @containers.each do |container| %>
		<tr>
			<td><%= container.name %></td>
			<td><%= container.description %></td>
			<% if container.running %>
				<td>Container is running.</td>
				<td><%= link_to 'Stop', stop_container_path(container), method: :delete, data: {
					confirm: 'Are you sure? Any active users will be kicked.' } %> </td>
				<td><%= link_to 'Show', container_path(container) %></td>
				<td><%= link_to 'Open Container', container_path(container) + '/view/', :target => :_blank %></td>
			<% else %>
				<td>Container is stopped.</td>
				<td><%= link_to 'Start', start_container_path(container), method: :put %></td>
				<td><%= link_to 'Show', container_path(container) %></td>
				<td></td>
			<% end %>
		</tr>
	<% end %>
</table>
<%= link_to 'Add Container', new_project_container_path(@project) %>

<br/>
<br/>
<%= link_to 'Edit', edit_project_path(@project) %>
| <%= link_to 'Back', projects_path %>